Adds estimate next purchase date feature
the-collab-lab/tcl-55-smart-shopping-list pull request #24
Opened 2023-05-02 03:57 UTC by ticiadev

_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description

## Related Issue

## Acceptance Criteria

- [x] When the user purchases an item, the item’s `dateNextPurchased` property is calculated using the `calculateEstimate` function and saved to the Firestore database
  - [x] `dateNextPurchased` is saved as **a date**, not a number
- [x] A `getDaysBetweenDates` function is exported from `utils/dates.js`  and imported into `api/firebase.js`
  - [x] This function takes two JavaScript Dates and return the number of days that have passed between them

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
| ✓   | :sparkles: New feature     |

## Updates

### Before

### After

## Testing Steps / QA Criteria

2023-05-05 18:52 UTC, katherineyuneman approved these changes
Looks good to me! Tested a few different items and each was adding correctly to firebase based on the days between dates.

2023-05-05 18:52 UTC, katherineyuneman commented on src/api/firebase.js
> +			data.dateLastPurchased?.toDate() ?? data.dateCreated.toDate(),
like how you set up the logic here

2023-05-06 14:57 UTC, mentalcaries commented on src/utils/dates.js
> +	const diff = Math.abs(date1Milliseconds - date2Milliseconds);
Nice check here for a negative result

2023-05-06 15:18 UTC, mentalcaries commented on src/api/firebase.js
Lookin good! It works well!

2023-05-06 17:59 UTC, Yaosaur commented on src/api/firebase.js
> +			data.dateLastPurchased?.toDate() ?? data.dateCreated.toDate(),
Nice use of both the optional chaining operator and nullish coalescing operator. I had to look into what they are/do, but definitely does make the code cleaner.

2023-05-06 18:38 UTC, Yaosaur requested changes
Everything works as expected, however just a couple of things I noticed when reviewing the code itself. Let me know if there are any questions.

2023-05-06 18:38 UTC, Yaosaur commented on src/api/firebase.js
> +		const data = docSnap.data();
So there's an unnecessary call to firebase here just to get the item attributes again. How can this be written better? Do we really need a check to docSnap.exists if the list is showing our list item?

2023-05-06 18:38 UTC, Yaosaur commented on src/api/firebase.js
> +				data.totalPurchases,
Take a look [https://www.npmjs.com/package/@the-collab-lab/shopping-list-utils?activeTab=code](url)

Really minor, but shouldn't total purchases be current purchase + 1, calculateEstimate assumes totalPurchases includes this current purchase.

2023-05-06 18:38 UTC, Yaosaur commented on src/utils/dates.js
> +	if (date1 === undefined || date2 === undefined) {
Do we need to check that both dates could be undefined? Based on how this function is used, would `dateNextPurchased` ever be undefined?

2023-05-07 21:49 UTC, 5hraddha approved these changes

2023-05-08 01:23 UTC, merged