Adds Chakra UI components for the Add Item page
the-collab-lab/tcl-55-smart-shopping-list pull request #43
Opened 2023-05-24 20:34 UTC by ticiadev

## Description

This code adds Chakra UI components to the Add Item and List pages. A drawer component has a button on the List page to access the Add Item page, where it has been updated with Chakra UI form and toast components. This simplifies the code by adding Chakra UI components that enhance the design and usability of the page, while also keeping a consistent interface with the rest of the application.

## Related Issue

Closes #38 
Closes #37 

## Acceptance Criteria

- [ ]  The Add Item page within the drawer includes fields for entering item details, such as name and the timeframe for buying the item again.
- [ ]  Chakra UI components for input fields should have appropriate styling, including labels, placeholders, and error handling.
- [ ]  The form should have a submit button, styled using Chakra UI, to allow users to submit the item details.
- [ ] The error and added messages should be displayed to the user using the chakra `toast` component.

- [ ]  A Chakra UI drawer component should be implemented to hold the Add Item page.
- [ ]  The drawer should be accessible from the List page, allowing users to open and close it.
- [ ]  When the drawer is opened, the Add Item page should be displayed within the drawer.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
| ✓   | :sparkles: New feature     |
| ✓   | :hammer: Refactoring       |

## Updates

### Before

### After

## Testing Steps / QA Criteria

2023-05-26 17:28 UTC, katherineyuneman approved these changes
Everything is looking great even on mobile size and functioning as it should!  I love the way the drawer pops out.

2023-05-28 12:40 UTC, Yaosaur requested changes
Works as intended on both desktop and mobile. Couple of changes requested, but otherwise great work!

2023-05-28 12:40 UTC, Yaosaur commented on src/components/AddItem.jsx
> +				title: 'No item name entered',
@katherineyuneman Same here, do you think having a title is necessary? If so, we should add one to list item page. I feel like takes more space and is basically a repeat of the description.

2023-05-28 12:40 UTC, Yaosaur commented on src/components/AddItem.jsx
> +		return true;
![image](https://github.com/the-collab-lab/tcl-55-smart-shopping-list/assets/99099243/f6a8ff19-144e-4600-ba81-ef4f86668201)

Miso is already on the list. I am expecting to see both `Please only use alphanumeric, ', -, or & characters in your item name.` and  `Miso** is already on your list as Miso.` Would probably be best to have as two separate toasts. In the original implementation we implemented as an array of error messages which was later looped. I think the same pattern can be followed but to return multiple toasts with the error messages.

For reference:
![image](https://github.com/the-collab-lab/tcl-55-smart-shopping-list/assets/99099243/2e43f5ff-6550-457c-ace2-48c7fdd26b93)

2023-05-28 12:40 UTC, Yaosaur commented on src/components/AddItem.jsx
> +								<Text htmlFor="itemName">Item Name:</Text>
Not focusing on pressing the label, try FormLabel instead.

2023-05-28 23:42 UTC, merged